M48
; DRILL file {KiCad 7.0.9} date Tue Nov 28 21:36:28 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-28T21:36:28+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X3.41Y-3.4
X3.81Y-3.4
X4.191Y-3.401
X4.591Y-3.401
T2
X3.4422Y-2.6806
X3.7887Y-2.6806
X4.211Y-2.681
X4.5575Y-2.681
T3
X3.61Y-3.4
X4.391Y-3.401
T0
M30
